language: elixir
elixir:
  - 1.3.4
otp_release:
  - 18.2.1
addons:
  postgresql: '9.4'
cache:
  directories:
  - node_modules
before_install:
  - cp config/secret.exs.example config/secret.exs
script:
  - bin/check
